language: go
install:
  - export HUGO_VERSION=0.37.1
  - export HUGO_PACKAGE=hugo_${HUGO_VERSION}_Linux-64bit
  - curl -L https://github.com/spf13/hugo/releases/download/v$HUGO_VERSION/$HUGO_PACKAGE.tar.gz | tar xz
  - ls 
  - mkdir -p $HOME/bin
  - mv ./hugo $HOME/bin/hugo
script:
  - hugo -s exampleSite

deploy:
  provider: pages
  skip_cleanup: true
  local-dir: "exampleSite/public"
  github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

notifications:
email: false

